'''
Created on Sep 8, 2010

@author: Michael Liao
'''

import re
import os
import logging
from Cheetah.Template import Template

PACKAGE_EXCLUDES = (
        r'^.*\.pyc$',                    # *.pyc
        r'^\/[a-zA-Z0-9\_]+\/view\/.*$', # /*/view/**
        r'^.*\_test$',                   # *_test
        r'^.*\_test\.py',                # *_test.py
        r'^\/build\.py$',                # /build.py
)

REGEX_EXCLUDES = []
for regex in PACKAGE_EXCLUDES:
    REGEX_EXCLUDES.append(re.compile(regex))

def main():
    '''
    Build ExpressMe by package() and deploy().
    '''
    root = os.path.split(__file__)[0]
    compile_view(root)
    package(root)

def package(root_path):
    '''
    Compile all views and make a zip file.
    '''
    fs = os.listdir(root_path)

def _filter(path, root_path):
    relative = path[len(root_path):].replace(os.sep, '/')
    for m in REGEX_EXCLUDES:
        if m.match(relative) is not None:
            return False
    return True

def compile_view(root_path):
    '''
    Compile all cheetah template to py files. Only work on local.
    '''
    autogen_path = os.path.join(root_path, 'autogen')
    all_subdirs = os.listdir(root_path)
    subdirs = [sub for sub in all_subdirs if os.path.isdir(os.path.join(root_path, sub, 'view'))]
    subdirs.sort()
    for sub in subdirs:
        _compile_dir(sub, os.path.join(root_path, 'view'), autogen_path)

def _compile_dir(modname, view_path, autogen_path):
    '''
    Compile a module which contains 'view' dir
    '''
    dist_path = os.path.join(autogen_path, modname)
    os.makedirs(dist_path)
    _gen_init_py(autogen_path)
    _gen_init_py(dist_path)
    files = os.listdir(view_path)
    views = [os.path.join(view_path, f) for f in files if f.endswith('.html') and os.path.isfile(os.path.join(view_path, f))]
    views.sort()
    for v in views:
        _compile_file(modname, autogen_path, v)

def _compile_file(modname, autogen_path, file_path):
    '''
    Mapping view file to a compiled Python module, for example:
    /blog/view/index.html -> /autogen/blog/index.py
    '''
    logging.info('Compile %s...' % file_path)
    cc = Template.compile(file=file_path, source=None, returnAClass=False, moduleName='autogen.' + modname, className='CompiledTemplate')
    name = os.path.basename(file_path)[:-4] + 'py'
    file = os.path.join(autogen_path, modname, name)
    f = open(file, 'w')
    f.write(cc)
    f.close()

def _mkdir(path):
    if path.isdir(path):
        return
    os.makedirs(path)

def _gen_init_py(package_path):
    file = open(os.path.join(package_path, '__init__.py'), 'w')
    file.write(r'''#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# DO NOT modify this file because it was generated by 'compile_view'
#
''')
    file.close()

if __name__ == '__main__':
    main()
